server:
  port: 8080
  servlet:
    context-path: /banking-app
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_cts_db
    username: root
    password: Keerthana@tcr21
    
  
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
